"""empty message

Revision ID: 8c3a6673485c
Revises: c24fc61cd79e
Create Date: 2023-10-31 22:45:31.551515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3a6673485c'
down_revision = 'c24fc61cd79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pedagang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_deleted', sa.Integer(), nullable=True))
        batch_op.drop_column('id_daleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pedagang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_daleted', sa.INTEGER(), nullable=True))
        batch_op.drop_column('id_deleted')

    # ### end Alembic commands ###
