"""empty message

Revision ID: 9d6e4ee44581
Revises: 8c3a6673485c
Create Date: 2023-10-31 22:47:11.294227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6e4ee44581'
down_revision = '8c3a6673485c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pedagang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), nullable=True))
        batch_op.drop_column('id_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pedagang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_deleted', sa.INTEGER(), nullable=True))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
