"""empty message

Revision ID: a79aa289d65c
Revises: 6d3e756b8240
Create Date: 2023-11-01 08:53:05.044000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79aa289d65c'
down_revision = '6d3e756b8240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pedagang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), nullable=True))
        batch_op.drop_column('id_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pedagang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_deleted', sa.INTEGER(), nullable=True))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
