"""empty message

Revision ID: b4e65f5a6f2e
Revises: 
Create Date: 2023-10-30 17:45:49.639192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e65f5a6f2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_pedagang',
    sa.Column('id_pedagang', sa.String(length=36), nullable=False),
    sa.Column('nama_pedagang', sa.String(length=255), nullable=True),
    sa.Column('alamat_pedagang', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_pedagang')
    )
    op.create_table('data_dagangan',
    sa.Column('id_dagangan', sa.String(length=36), nullable=False),
    sa.Column('banyak_dagangan', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_pedagang', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_pedagang'], ['data_pedagang.id_pedagang'], ),
    sa.PrimaryKeyConstraint('id_dagangan')
    )
    op.create_table('data_setoran',
    sa.Column('id_setoran', sa.String(length=36), nullable=False),
    sa.Column('jumlah_setoran', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_pedagang', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_pedagang'], ['data_pedagang.id_pedagang'], ),
    sa.PrimaryKeyConstraint('id_setoran')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_setoran')
    op.drop_table('data_dagangan')
    op.drop_table('data_pedagang')
    # ### end Alembic commands ###
